In [2]:
import numpy as np

In [9]:
#creating an 1D array 
a = np.array([1,2,3,4,5])
print(type(a))
print(a)
print(a.ndim)

<class 'numpy.ndarray'>
[1 2 3 4 5]
1


In [11]:
b = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(b)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
2
(3, 3)


In [12]:
print(b.ndim)


2


In [13]:
print(b.shape) #array shape (rows, columns)

(3, 3)


In [14]:
b.itemsize # bytes occupied by single element in array

4

In [15]:
b.size * b.itemsize # bytes occupied by all elements in array

36

In [16]:
b.nbytes # bytes occupied by all elements in array

36

# Accessing/Changing elements , rows& columns

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a.shape

(2, 7)

In [21]:
#Get aspecific element
a[1,5]

13

In [22]:
a[1,-2]

13

In [26]:
#Get a specific row
a[0,:]


array([1, 2, 3, 4, 5, 6, 7])

In [27]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [28]:
#Get specific column
a[:,1]

array([2, 9])

In [29]:
# Slicing the row
a[0,1:4]

array([2, 3, 4])

In [31]:
#Inser new value
a[0,0] = 100
print(a)

[[100   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14]]


In [35]:
# Zero matrix
zeroMatrix = np.zeros((3,3))
print(zeroMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
# Single element array
sEMatrix = np.full((3,3),99)
print(sEMatrix)

[[99 99 99]
 [99 99 99]
 [99 99 99]]


In [39]:
#matrix with same size of a and elements are replaced with 77
np.full_like(a,77)

array([[77, 77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77, 77]])

In [40]:
# Generate random element matrix floats
np.random.rand(4,3)

array([[0.67203714, 0.88933469, 0.21880997],
       [0.5461347 , 0.01405043, 0.29933596],
       [0.87525474, 0.6358934 , 0.28614348],
       [0.21106908, 0.71520358, 0.93274955]])

In [48]:
# Generate random element matrix floats
np.random.randint(100,size = (4,3))

array([[62, 94, 17],
       [69, 66,  1],
       [91, 76, 94],
       [31, 91, 81]])

In [49]:
#Identity Matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
a = np.array([1,2,3,4,5])
a +2 

array([3, 4, 5, 6, 7])

In [51]:
a -2 

array([-1,  0,  1,  2,  3])

In [52]:
a *2 

array([ 2,  4,  6,  8, 10])

In [53]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [54]:
a%2

array([1, 0, 1, 0, 1], dtype=int32)

In [55]:
# Matrix mul
a = np.array([[1 ,2,3],[4,5,6],[7,8,9]])
product = np.matmul(a,a)
print(product)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [57]:
#Det of a matrix
np.linalg.det(product)

-3.0610808006017985e-13